DROP TABLE IF EXISTS rsvp CASCADE;
CREATE TABLE rsvp(
  guest_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  guest_name TEXT,
  plus_one INTEGER REFERENCES rsvp(guest_id),
  email TEXT,
  invited_to_brunch BOOLEAN,
  brunch TEXT,
  brunch_time TIMESTAMPTZ,
  wedding TEXT,
  wedding_time TIMESTAMPTZ,
  vaxxed TEXT,
  vaxxed_time TIMESTAMPTZ,
  masked TEXT,
  masked_time TIMESTAMPTZ,
  hike TEXT,
  hike_time TIMESTAMPTZ,
  phone TEXT,
  phone_time TIMESTAMPTZ,
  cocktails TEXT,
  cocktails_time TIMESTAMPTZ,
  cocktails_excess TEXT,
  cocktails_excess_time TIMESTAMPTZ
);

DROP TABLE IF EXISTS submitted_rsvp;
CREATE TABLE submitted_rsvp(
  rsvp_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  guest_id INTEGER REFERENCES rsvp(guest_id),
  brunch BOOLEAN,
  wedding BOOLEAN,
  hike BOOLEAN,
  vaxxed BOOLEAN,
  masked BOOLEAN,
  cocktails BOOLEAN,
  cocktail_excess INTEGER,
  time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
